name: Build and Release Exe

on:
  push:
    tags:
      - 'v*' # Kích hoạt khi đẩy tag dạng v1.0.0, v1.0.1, v2.0.0...

permissions:
  contents: write # Cấp quyền ghi để tạo Release và tải lên file assets

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python numpy==1.26.4 pillow pytesseract pure-python-adb adbutils requests pyautogui keyboard mouse pyinstaller onnx

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller gui_auto_config.spec

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/gui_auto_config.exe
        body_path: release_notes.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
